Adding documnetation for Advanced Provenance Queries
provena/provena pull request #28
Opened 2023-08-31 06:47 UTC by Rosspet

# Provena PR (Minor): Adding documnetation for Advanced Provenance Queries

## Checklist

-   [ ] If tests are required for this change, are they implemented?
-   [ ] Are user documentation changes required, if so, is there a task to track it and/or is it completed?
-   [ ] If migrations are required, is the process documented below?
-   [ ] If developer/system documentation updates are required, is there a task to track it and/or is it completed?
-   [ ] At least one developer has reviewed this change (unless PR is being used to mark a commit point without need for review)?
-   [ ] If change requires update to the [manual testing runsheet](https://confluence.csiro.au/pages/viewpage.action?pageId=1701138616), is there a task to track it and/or is it completed?

## Description

Adding documentation for advanced provenance queries. Before, merging, please serve the documentation and ensure the images are displaying appropriately.

2023-08-31 07:03 UTC, PeterBaker0 requested changes
Couple of minor wording changes but looks good 👍

2023-08-31 07:03 UTC, PeterBaker0 commented on docs/provenance/exploring-provenance/exploring-record-lineage.md
> +In addition to interrogation of provenance via normal queries facilitated by the manual expansion of entities, the Provenance System supplies special querying capabilities for automatically discernin
I think this wording could be simplified. Particularly this bit "interrogation of provenance via normal queries facilitated by the manual expansion of entities, the Provenance System supplies special querying capabilities for automatically discerning affected downstream or upstream Datasets and Agents"

Also maybe we should be consistent re: "advanced" vs "special" queries - I don't mind which.

2023-08-31 07:03 UTC, PeterBaker0 commented on docs/provenance/exploring-provenance/exploring-record-lineage.md
> +These queries can be made from a starting node by single clicking and using the "Provenance Queries" drop down (which appears on the right panel) to select the desired query. For example, selecting a
I think this sentence could be simplified

> will return all the upstream lineage of connected datasets that were (by definition of upstream) occuring before, or used to produce or contribute towards this input dataset.

Maybe just "will return all upstream datasets which were used to produce, or contributed to the production of the selected dataset."

2023-08-31 23:49 UTC, PeterBaker0 commented
I'll pick up on this and close this out as Ross is unavailable until later next week

2023-09-01 00:10 UTC, PeterBaker0 approved these changes
Simplified wording and cleaned up old artifacts from previous docs.

2023-09-01 00:10 UTC, merged

2023-09-01 02:38 UTC, jyucsiro commented
nice work!