Provena Minor Release v2.1
provena/provena pull request #30
Opened 2023-09-29 02:16 UTC by PeterBaker0

# Provena PR (Minor): v2.1 Minor Release

## Major Features
- Dataset metadata extension - includes a suite of new optional fields to enrich dataset metadata, reaching closer to ISO 19115 compatibility

## Minor Features
- Right clickable cards in the Registry UI list view
- New interface for directly entering the ID of an item in the registry rather than searching
- Better handling of long descriptions for datasets
- Improved styling for new activity subtypes Create and Version

## Bug Fixes
- Use of utf-16 encoding for email text in email service, enabling emojis etc
- Improved auth error handling in user link workflow

## Other
- Improved testing for dataset releases
- Update links in docs

## Contributors

- @Rosspet 
- @xinyuhoulucy 
- @PeterBaker0 

## Includes the following PRs:

RRAPIS-1511 (Minor): Right Clickable Items in Registry (#48)
RRAPIS-1492 (Bug Fix): Emoji email (#47)
RRAPIS-1524 (Major): Dataset Metadata Extension (#46)
RRAPIS-1493 (Minor): Dataset Release Tests (#44)
RRAPIS-1410 (Minor): Fetch item feature in registry UI (#43)
RRAPIS-1506 (Minor): Wrap dataset description with expand in dataset list and overview tab (#42)
RRAPIS-1498 (Minor): Create and version styling (#40)
RRAPIS-1374 (Minor): New-user-profile-identity-link-read-permission-problem (#39)
RRAPIS-1491 (Minor): Update-doc-links-in-all-uis (#38)

2023-09-29 03:20 UTC, xinyuhoulucy requested changes
Looks all good to me, just need to make sure the interface names in ```data-store-ui/src/shared-interfaces/registryModels.ts``` is correct as we expected.

2023-10-04 22:05 UTC, PeterBaker0 commented on data-store-ui/src/stores/registerOrModifyStore.ts
> +import { CollectionFormat } from "shared-interfaces/registryModels";
Yes? I think it's fine - not sure what you mean. These import changes is just due to organise imports renaming/moving things around.

2023-10-04 22:05 UTC, PeterBaker0 commented on prov-ui/src/shared-interfaces/RegistryModels.ts
> +export interface DatasetMetadata {
Okay

2023-10-04 22:42 UTC, xinyuhoulucy approved these changes

2023-10-05 03:42 UTC, PeterBaker0 commented on data-store-ui/src/stores/registerOrModifyStore.ts
> +import { CollectionFormat } from "shared-interfaces/registryModels";
After discussion with you I understand the issue here - great pickup thanks.

Have fixed in subsequent update.

2023-10-05 03:43 UTC, merged